### PR TITLE
Implement `s`, fix `A` at end of line, fix `o`, fix `C` on single-char

### LINKED ISSUE #57: `C` command causes `BoundsError` on 1-character buffers
Using `C` in Normal mode on a buffer with 1 character in it causes a `BoundsError`

```julia
julia> VimBindings.PkgTools.run("C", VimBindings.TextUtils.testbuf("|A"))
ERROR: BoundsError: attempt to access 32-element Vector{UInt8} at index [0:0]
Stacktrace:
  [1] throw_boundserror(A::Vector{UInt8}, I::Tuple{UnitRange{Int64}})
    @ Base ./abstractarray.jl:744
  [2] checkbounds
    @ ./abstractarray.jl:709 [inlined]
  [3] getindex
    @ ./array.jl:921 [inlined]
  [4] splice!(a::Vector{UInt8}, r::UnitRange{Int64}, ins::Base.CodeUnits{UInt8, String})
    @ Base ./array.jl:1743
  [5] edit_splice!(s::Union{REPL.LineEdit.MIState, REPL.LineEdit.ModeState, IOBuffer}, r::Pair{Int64, Int64}, ins::String; rigid_mark::Bool)
    @ REPL.LineEdit ~/.julia/juliaup/julia-1.9.0+0.x64.linux.gnu/share/julia/stdlib/v1.9/REPL/src/LineEdit.jl:764
  [6] edit_splice! (repeats 2 times)
    @ ~/.julia/juliaup/julia-1.9.0+0.x64.linux.gnu/share/julia/stdlib/v1.9/REPL/src/LineEdit.jl:744 [inlined]
  [7] macro expansion
    @ ~/.julia/packages/VimBindings/Q2T3Z/src/util.jl:39 [inlined]
  [8] delete(buf::IOBuffer, motion::VimBindings.Motions.Motion)
    @ VimBindings.Operators ~/.julia/packages/VimBindings/Q2T3Z/src/operator.jl:31
  [9] change(buf::IOBuffer, motion::VimBindings.Motions.Motion)
    @ VimBindings.Operators ~/.julia/packages/VimBindings/Q2T3Z/src/operator.jl:22
 [10] macro expansion
    @ ~/.julia/packages/VimBindings/Q2T3Z/src/util.jl:39 [inlined]
 [11] execute(buf::IOBuffer, command::VimBindings.Commands.OperatorCommand)
    @ VimBindings.Execution ~/.julia/packages/VimBindings/Q2T3Z/src/execute.jl:123
 [12] execute(buf::IOBuffer, command::VimBindings.Commands.SynonymCommand)
    @ VimBindings.Execution ~/.julia/packages/VimBindings/Q2T3Z/src/execute.jl:142
 [13] run(cmd::String, buf::VimBindings.TextUtils.Buffer.VimBuffer)
    @ VimBindings.PkgTools ~/.julia/packages/VimBindings/Q2T3Z/src/pkgtools.jl:34
 [14] top-level scope
    @ REPL[6]:1
```

Here is a similar exception caused by using `C` in the REPL
```julia
julia> ┌ Error: Error while executing vim key strike
│   exception =
│    BoundsError: attempt to access 66-element Vector{UInt8} at index [0:0]
│    Stacktrace:
│      [1] throw_boundserror(A::Vector{UInt8}, I::Tuple{UnitRange{Int64}})
│        @ Base ./abstractarray.jl:744
│      [2] checkbounds
│        @ ./abstractarray.jl:709 [inlined]
│      [3] getindex
│        @ ./array.jl:921 [inlined]
│      [4] splice!(a::Vector{UInt8}, r::UnitRange{Int64}, ins::Base.CodeUnits{UInt8, String})
│        @ Base ./array.jl:1743
│      [5] edit_splice!(s::Union{REPL.LineEdit.MIState, REPL.LineEdit.ModeState, IOBuffer}, r::Pair{Int64, Int64}, ins::String; rigid_mark::Bool)
│        @ REPL.LineEdit ~/.julia/juliaup/julia-1.9.0+0.x64.linux.gnu/share/julia/stdlib/v1.9/REPL/src/LineEdit.jl:764
│      [6] edit_splice! (repeats 2 times)
│        @ ~/.julia/juliaup/julia-1.9.0+0.x64.linux.gnu/share/julia/stdlib/v1.9/REPL/src/LineEdit.jl:744 [inlined]
│      [7] macro expansion
│        @ ~/.julia/packages/VimBindings/Q2T3Z/src/util.jl:39 [inlined]
│      [8] delete(buf::IOBuffer, motion::VimBindings.Motions.Motion)
│        @ VimBindings.Operators ~/.julia/packages/VimBindings/Q2T3Z/src/operator.jl:31
│      [9] change(buf::IOBuffer, motion::VimBindings.Motions.Motion)
│        @ VimBindings.Operators ~/.julia/packages/VimBindings/Q2T3Z/src/operator.jl:22
│     [10] macro expansion
│        @ ~/.julia/packages/VimBindings/Q2T3Z/src/util.jl:39 [inlined]
│     [11] execute(buf::IOBuffer, command::VimBindings.Commands.OperatorCommand)
│        @ VimBindings.Execution ~/.julia/packages/VimBindings/Q2T3Z/src/execute.jl:123
│     [12] execute(buf::IOBuffer, command::VimBindings.Commands.SynonymCommand)
│        @ VimBindings.Execution ~/.julia/packages/VimBindings/Q2T3Z/src/execute.jl:142
│     [13] strike_key(c::String, s::REPL.LineEdit.MIState)
│        @ VimBindings ~/.julia/packages/VimBindings/Q2T3Z/src/VimBindings.jl:118
│     [14] macro expansion
│        @ ~/.julia/packages/VimBindings/Q2T3Z/src/util.jl:39 [inlined]
│     [15] (::VimBindings.var"#2#4"{Dict{Char, Any}, VimBindings.var"#1#3"{REPL.LineEdit.var"#139#195", String}, String})(s::REPL.LineEdit.MIState, p::REPL.LineEditREPL)
│        @ VimBindings ~/.julia/packages/VimBindings/Q2T3Z/src/lineeditalt.jl:72
│     [16] macro expansion
│        @ ~/.julia/packages/VimBindings/Q2T3Z/src/util.jl:39 [inlined]
│     [17] prompt!(term::REPL.Terminals.TTYTerminal, prompt::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
│        @ VimBindings ~/.julia/packages/VimBindings/Q2T3Z/src/lineeditalt.jl:27
│     [18] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
│        @ REPL.LineEdit ~/.julia/juliaup/julia-1.9.0+0.x64.linux.gnu/share/julia/stdlib/v1.9/REPL/src/LineEdit.jl:2642
│     [19] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
│        @ REPL ~/.julia/juliaup/julia-1.9.0+0.x64.linux.gnu/share/julia/stdlib/v1.9/REPL/src/REPL.jl:1300
│     [20] (::REPL.var"#62#68"{REPL.LineEditREPL, REPL.REPLBackendRef})()
│        @ REPL ./task.jl:514
└ @ VimBindings ~/.julia/packages/VimBindings/Q2T3Z/src/lineeditalt.jl:74
```

### LINKED ISSUE #60: `o` includes the final character of a line in the new line
running `o` like:

```julia
julia> function |hello()
```
results in

```julia
julia> function hello(
|)
```

instead of

```julia
julia> function hello()
|
```

### LINKED ISSUE #61: `A` moves backwards when cursor is at end of line
I have noticed a strange behavior when using the `A` key where, when in normal mode and with the cursor past the end of the line:
```julia
julia> println()█
```
and then hitting `A`, will have the insert mode cursor aligned one back:
```julia
julia> println(|)
```
rather than
```julia
julia> println()|
```
However, when the cursor is anywhere else, such as the second-to-last position:
```julia
julia> println(█
```
or earlier:
```julia
julia> prin█ln()
```
it will successfully move to the end:
```julia
julia> println()|
```

### PR DESCRIPTION
**Pull request by caleb-allen**
This fixes #57, fixes #60 and fixes #61 by reworking how lines are detected using the "junction" logic in textutils.jl.

Also makes a variety of smaller improvements.
- [x] Add `s` command
- [x] fix `o` command
- [x] improve UTF-8 handling
- [x] Refactor `word_next` to use `junction` logic from TextUtils
- [x] Refactor other motion commands to use `junction` logic from TextUtils
- [x] Add `read_left`, `read_right`, `peek_left`, `peek_right` to improve utf8 handling in buffer operations

### CODE REVIEW

File: src/motion.jl [hunk 1]
```diff
@@ -714,14 +685,14 @@ is also considered to be a word.
...
 function word(buf::IO)::Motion
     origin = position(buf)
-    start = if is_object_start(buf)
+    start = if is_word_start(buf)
         Motion(buf)
     else
         word_back(buf)
     end
     eof(buf) && return start
     skip(buf, 1)
```
Comment (caleb-allen) [inline src/motion.jl:694]: Convert to `read_right`

File: src/motion.jl [hunk 2]
```diff
@@ -714,14 +685,14 @@ is also considered to be a word.
...
-    @loop_guard while !eof(buf) && is_in_object(buf)
+    @loop_guard while !eof(buf) && is_in_word(buf)
         skip(buf, 1)
```
Comment (caleb-allen) [inline src/motion.jl:696]: Convert to `read_right`

File: src/motion.jl [hunk 3]
```diff
@@ -743,15 +714,15 @@ function WORD(buf::IO)::Motion
     is_whitespace(peek(buf, Char)) && return Motion(origin, origin)
 
     local start
-    @loop_guard while !is_non_whitespace_start(buf)
+    @loop_guard while !is_object_start(buf)
         skip(buf, -1)
```
Comment (caleb-allen) [inline src/motion.jl:718]: Convert to `read_right`

File: src/motion.jl [hunk 4]
```diff
@@ -743,15 +714,15 @@ function WORD(buf::IO)::Motion
...
     end
     start = position(buf)
     seek(buf, origin)
 
 
     local endd
-    @loop_guard while !is_non_whitespace_end(buf)
+    @loop_guard while !is_object_end(buf)
         skip(buf, 1)
```
Comment (caleb-allen) [inline src/motion.jl:726]: Convert to `read_right`

File: src/motion.jl [hunk 5]
```diff
@@ -788,35 +759,17 @@ end
...
-    end
-
-    @loop_guard while !eof(buf) && position(buf) > 0
-        c = peek(buf, Char)
-        if is_linebreak(c)
-            skip(buf, 1)
-            break
-        end
+    while !is_line_start(buf)
         LE.char_move_left(buf)
```
Comment (caleb-allen) [inline src/motion.jl:763]: Convert to `read_left`

File: src/motion.jl [hunk 6]
```diff
@@ -788,35 +759,17 @@ end
...
-
-    # find the line end
-    @loop_guard while !eof(buf)
-        c = read(buf, Char)
-        if is_linebreak(c)
-            LE.char_move_left(buf)
-            break
-        end
+    while !is_line_end(buf)
+        LE.char_move_right(buf)
```
Comment (caleb-allen) [inline src/motion.jl:768]: Convert to `read_right`

File: src/textutils.jl [hunk 7]
```diff
@@ -45,32 +53,36 @@ Get the
...
+   #     # beginning of buffer
+   #     c0 = nothing
+   # else
+   #     # skip(buf, -1)
+   #     for b in 1:char_byte_count
+   #                     
+   #     end
+   #     # c0 = read(buf, Char) |> TextChar
+   #     seek(buf, origin)
+   # end
```
Comment (caleb-allen) [inline src/textutils.jl:76]: Remove commented lines

File: src/operator.jl [hunk 8]
```diff
@@ -19,16 +19,31 @@ function operator_fn(c::Char)::Function
...
 
 # also, when there is whitespace following a word,
 # "dw" deletes that whitespace
 # and "cw" only removes the inner word
 function delete(buf::IO, motion::Motion) #, motion_type :: MotionType)
+    text = String(take!(copy(buf)))
+    left = min(motion)
+    # if length(cs) > max(motion)
+    #     if motion.motiontype == linewise && cs[max(motion)] == '\n'
+    #         right = max(motion) + 1
```
Comment (caleb-allen) [inline src/operator.jl:41]: Remove commented lines

File: src/operator.jl [hunk 9]
```diff
@@ -49,16 +64,17 @@ function yank(buf::IO, motion::Motion)::Union{String,Nothing}
     return text
 end
 
-function insert(buf::IO, pos::Integer, text)
-    s = string(text)
+insert(buf::IO, pos::Int, c::Char) = insert(buf, pos, string(c))
+function insert(buf::IO, pos::Int, s::String)
+    # seek()
```
Comment (caleb-allen) [inline src/operator.jl:69]: Remove

File: src/pkgtools.jl [hunk 10]
```diff
@@ -91,7 +92,8 @@ using PrecompileTools
         for (cmd, buf) in commands
             well_formed(cmd)
             partial_well_formed(cmd)
-            
+
+            @info "Precompiling cmd" cmd
```
Comment (caleb-allen) [inline src/pkgtools.jl:96]: Remove
